export const items = [
    {
        id: 1,
        title: "CHAIR",
        name: "hero-slider-1_vqr99h.jpg",
        price: "78",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448519/ecommerce/images/hero-slider/home-1/hero-slider-1_vqr99h.jpg',
        description:"",
    },
    {
        id: 2,
        title: "",
        name: "service-promo-1_qqg5wa.png",
        price: "90",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448534/ecommerce/images/icons/service-promo-1_qqg5wa.png',
        description:"",
    },
    {
        id: 3,
        title: "",
        name: "service-promo-2_dguybd.png",
        price: "67",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448535/ecommerce/images/icons/service-promo-2_dguybd.png',
        description:"",
    },
    {
        id: 4,
        title: "",
        name: "service-promo-3_haxseb.png",
        price: "56",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448535/ecommerce/images/icons/service-promo-3_haxseb.png',
        description:"",
    },
    {
        id: 5,
        title: "",
        name: "service-promo-4_qz6cul.png",
        price: "80",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448536/ecommerce/images/icons/service-promo-4_qz6cul.png',
        description:"",
    },
    {
        id: 6,
        title: "STUDY LAMP",
        name: "banner-style-1-img-1_i3a9tx.jpg",
        price: "98",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448498/ecommerce/images/banner/banner-style-1-img-1_i3a9tx.jpg',
        description:"",
    },
    {
        id: 7,
        title: "Kitchen utensils",
        name: "banner-style-2-img-1_c31a7t.jpg",
        price: "110",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448500/ecommerce/images/banner/banner-style-2-img-1_c31a7t.jpg',
        description:"",
    },
    {
        id: 8,
        title: "Sofas and Armchairs",
        name: "banner-style-2-img-2_chrq6g.jpg",
        price: "121",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448500/ecommerce/images/banner/banner-style-2-img-2_chrq6g.jpg',
        description:"",
    },
    {
        id: 9,
        title: "Chair & Bar stools",
        name: "banner-style-2-img-3_psifln.jpg",
        price: "191",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448501/ecommerce/images/banner/banner-style-2-img-3_psifln.jpg',
        description:"",
    },
    {
        id: 10,
        title: "Interior lighting",
        name: "banner-style-2-img-4_mjrdre.jpg",
        price: "80",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448501/ecommerce/images/banner/banner-style-2-img-4_mjrdre.jpg',
        description:"",
    },


//The new arrivals----------------------------------------------------------------------------------------


    {
        id: 11,
        title: "ALIQUAM LOBORTIS",
        name: "default-2_xbx8ug.jpg",
        price: "85.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448550/ecommerce/images/product/default/home-1/default-2_xbx8ug.jpg',
        description:"",
    },
    {
        id: 12,
        title: "CONDIMENTUM PERFUME",
        name: "default-3_ozxnq5.jpg",
        price: "60.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448551/ecommerce/images/product/default/home-1/default-3_ozxnq5.jpg',
        description:"",
    },
    {
        id: 13,
        title: "ELECTRIC KETTLE",
        name: "default-5_tkuhet.jpg",
        price: "100.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448552/ecommerce/images/product/default/home-1/default-5_tkuhet.jpg',
        description:"",
    },
    {
        id: 14,
        title: "WINDED CHAIR",
        name: "default-7_c2a9rc.jpg",
        price: "73.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448553/ecommerce/images/product/default/home-1/default-7_c2a9rc.jpg',
        description:"",
    },
    {
        id: 15,
        title: "ELECTRIC KETTLE",
        name: "default-5_tkuhet.jpg",
        price: "73.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448552/ecommerce/images/product/default/home-1/default-5_tkuhet.jpg',
        description:"",
    },
    {
        id: 16,
        title: "WINDED CHAIR",
        name: "default-6_trxrxk.jpg",
        price: "73.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448553/ecommerce/images/product/default/home-1/default-6_trxrxk.jpg',
        description:"",
    },
    {
        id: 17,
        title: "CONDIMENTUM PERFUME",
        name: "default-3_ozxnq5.jpg",
        price: "73.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448551/ecommerce/images/product/default/home-1/default-3_ozxnq5.jpg',
        description:"",
    },
    {
        id: 18,
        title: "ELECTRIC KETTLE",
        name: "default-4_uddr4u.jpg",
        price: "73.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448552/ecommerce/images/product/default/home-1/default-4_uddr4u.jpg',
        description:"",
    },

//Modern Furniture Basic Collection----------------------------------------------------------------------

    {
        id: 19,
        title: "Modern Furniture Basic Collection",
        name: "banner-style-3-img-1_snhlfc.jpg",
        price: "70",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448502/ecommerce/images/banner/banner-style-3-img-1_snhlfc.jpg',
        description:"",
    },

//best seller---------------------------------------------------------------------------------------------

    {
        id: 20,
        title: "BAR STOOL",
        name: "default-9_jimsmt.jpg",
        price: "85.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448554/ecommerce/images/product/default/home-1/default-9_jimsmt.jpg',
        description:"",
    },
    {
        id: 21,
        title: "ARMCHAIRS",
        name: "default-11_okansx.jpg",
        price: "60.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448548/ecommerce/images/product/default/home-1/default-11_okansx.jpg',
        description:"",
    },
    {
        id: 22,
        title: "LIGHTING",
        name: "default-5_tkuhet.jpg",
        price: "100.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448552/ecommerce/images/product/default/home-1/default-5_tkuhet.jpg',
        description:"",
    },
    {
        id: 23,
        title: "EASY CHAIRS",
        name: "default-6_trxrxk.jpg",
        price: "73.00",
        imgURL: 'https://res.cloudinary.com/dhrugutmv/image/upload/v1718448553/ecommerce/images/product/default/home-1/default-6_trxrxk.jpg',
        description:"",
    },

//product categories------------------------------------------------------------------------------------

    {
        id: 24,
        title: "",
        name: "",
        price: "",
        imgURL: '',
        description:"",
    },
    {
        id: 25,
        title: "",
        name: "",
        price: "",
        imgURL: '',
        description:"",
    },
    {
        id: 26,
        title: "",
        name: "",
        price: "",
        imgURL: '',
        description:"",
    },
]